"use client";

import { useEffect, useState } from "react";
import { Bookmark, BookOpen, ExternalLink, Play, RotateCcw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { HEXAGRAMS, TRIGRAM_INFO, hexagramByNumber, hexagramByLines, hexagramSymbol, trigramLabel } from "@/lib/hexagrams";
import { HEXAGRAM_NOTES } from "@/lib/hexagram-notes";
import { TOPICS, LESSONS, GLOSSARY, RESOURCES, CASES, type Topic } from "@/lib/knowledge";
import { patternSnapshot, type KeepResult } from "@/lib/results";
import type { Language } from "@/lib/iching";

type Tab = "hexagrams" | "learn" | "terms" | "resources" | "cases";
const TABS: { id: Tab; label: [string, string] }[] = [{ id: "hexagrams", label: ["六十四卦", "64 hexagrams"] }, { id: "learn", label: ["入门路径", "Learn"] }, { id: "terms", label: ["术语问答", "Terms & FAQ"] }, { id: "resources", label: ["精选资料", "Resources"] }, { id: "cases", label: ["案例练习", "Cases"] }];
type Route = { tab: Tab; hexagram: number | null; lesson: string | null; caseId: string | null; topic: Topic | "all" };
const DEFAULT_ROUTE: Route = { tab: "hexagrams", hexagram: null, lesson: null, caseId: null, topic: "all" };
function routeFromHash(): Route {
  if (typeof window === "undefined") return DEFAULT_ROUTE;
  const [, tab, target] = window.location.hash.slice(1).split("/");
  if (tab === "hexagram" && Number.isInteger(Number(target)) && Number(target) >= 1 && Number(target) <= 64) return { ...DEFAULT_ROUTE, hexagram: Number(target) };
  if (!TABS.some(t => t.id === tab)) return DEFAULT_ROUTE;
  const lesson = tab === "learn" ? LESSONS.find(l => l.id === target) : undefined;
  return { ...DEFAULT_ROUTE, tab: tab as Tab, topic: lesson?.topic ?? (TOPICS.some(t => t.id === target) ? target as Topic : "all"), lesson: lesson?.id ?? null, caseId: tab === "cases" && CASES.some(c => c.id === target) ? target : null };
}
export function MiniHexagram({ lines }: { lines: number[] }) { return <span className="mini-hexagram" aria-hidden="true">{[...lines].reverse().map((n, i) => <span key={i} className={n ? "mini-yang" : "mini-yin"}><i />{!n && <i />}</span>)}</span>; }

export function KnowledgeLibrary({ lang, onKeep, onGo }: { lang: Language; onKeep: KeepResult; onGo: (topic: Topic) => void }) {
  const [route, setRoute] = useState<Route>(DEFAULT_ROUTE);
  const [query, setQuery] = useState("");
  const [upper, setUpper] = useState("all");
  const [lower, setLower] = useState("all");
  const [page, setPage] = useState(0);
  const [moving, setMoving] = useState<number[]>([]);
  const [building, setBuilding] = useState(false);
  const [revealed, setRevealed] = useState(6);
  const li = lang === "zh" ? 0 : 1;
  const t = (zh: string, en: string) => lang === "zh" ? zh : en;
  const topicLabel = (topic: Topic) => TOPICS.find(p => p.id === topic)!.label[li];
  useEffect(() => { const sync = () => { setRoute(routeFromHash()); setQuery(""); setPage(0); }; sync(); window.addEventListener("hashchange", sync); return () => window.removeEventListener("hashchange", sync); }, []);
  useEffect(() => { setMoving([]); setBuilding(false); setRevealed(6); }, [route.hexagram]);
  useEffect(() => { if (!building) return; const timer = window.setInterval(() => setRevealed(v => Math.min(6, v + 1)), 350); return () => window.clearInterval(timer); }, [building]);
  useEffect(() => { if (revealed === 6) setBuilding(false); }, [revealed]);
  function open(tab: Tab | "hexagram", target?: string | number) {
    window.location.hash = `library/${tab}${target === undefined ? "" : `/${target}`}`;
    setRoute(routeFromHash()); setQuery(""); setPage(0); window.scrollTo({ top: 0, behavior: "instant" });
  }
  function chooseTopic(value: string) { open(route.tab, value === "all" ? undefined : value); }
  function animate() { if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) { setRevealed(6); return; } setRevealed(0); setBuilding(true); }
  const q = query.trim().toLowerCase();
  const filtered = HEXAGRAMS.filter(h => (upper === "all" || h.upper === upper) && (lower === "all" || h.lower === lower) && (!q || [h.name, h.traditional, String(h.number), h.upper, h.lower, TRIGRAM_INFO[h.upper].image[0], TRIGRAM_INFO[h.lower].image[0], HEXAGRAM_NOTES[h.number - 1].title, ...HEXAGRAM_NOTES[h.number - 1].summary].join(" ").toLowerCase().includes(q)));
  const inTopic = (topic: Topic) => route.topic === "all" || route.topic === topic;
  const terms = GLOSSARY.filter(g => inTopic(g.topic) && (!q || [...g.term, ...g.meaning, ...g.example].join(" ").toLowerCase().includes(q)));
  const resources = RESOURCES.filter(r => inTopic(r.topic) && (!q || [...r.title, ...r.author, ...r.description, ...r.edition].join(" ").toLowerCase().includes(q)));
  const base = route.hexagram ? hexagramByNumber(route.hexagram) : null;
  const current = base ? hexagramByLines(base.lines.map((n, i) => moving.includes(i + 1) ? 1 - n : n)) : null;
  const note = current ? HEXAGRAM_NOTES[current.number - 1] : null;
  const lesson = LESSONS.find(l => l.id === route.lesson);
  const caseStudy = CASES.find(c => c.id === route.caseId);
  const topicPicker = <Select value={route.topic} onValueChange={chooseTopic}><SelectTrigger aria-label={t("筛选内容分类", "Filter by topic")}><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{t("全部分类", "All topics")}</SelectItem>{TOPICS.map(p => <SelectItem value={p.id} key={p.id}>{p.label[li]}</SelectItem>)}</SelectContent></Select>;
  const search = (placeholder: string) => <div className="book-search"><Search size={18} aria-hidden="true" /><Input value={query} onChange={e => { setQuery(e.target.value); setPage(0); }} placeholder={placeholder} aria-label={placeholder} maxLength={100} /></div>;
  return <section className="book-page" aria-labelledby="book-heading">
    <div className="page-heading book-heading"><div><p className="eyebrow">THE COSMIC LIBRARY</p><h1 id="book-heading">{t("星图书阁", "The cosmic library")}</h1><p>{t("读懂一种结构，再把理解带回自己的生活。", "Understand a pattern, then bring your reading back to life.")}</p></div><span className="book-counts">64 {t("卦", "patterns")}<i />12 {t("篇入门", "lessons")}</span></div>
    <Tabs value={route.tab} onValueChange={value => open(value as Tab)}><TabsList className="book-tabs">{TABS.map(tab => <TabsTrigger key={tab.id} value={tab.id}>{tab.label[li]}</TabsTrigger>)}</TabsList><TabsContent value={route.tab}>

    {route.tab === "hexagrams" && !base && <>
      <div className="book-intro-row"><div><h2>{t("六十四卦，逐卦展开。", "Explore all 64 patterns.")}</h2><p>{t("卦名、上下卦、原文和白话导读；点开后可改变任一爻。", "Names, trigrams, classical texts, and notes. Open a pattern to change any line.")}</p></div><Button variant="outline" onClick={() => open("learn", "iching")}><BookOpen size={17} />{t("先读入门", "Start with the basics")}</Button></div>
      <div className="hexagram-filters">{search(t("搜索卦名、卦序或导读关键词", "Search names, numbers, or themes"))}<div><Label htmlFor="filter-upper">{t("上卦", "Upper")}</Label><Select value={upper} onValueChange={v => { setUpper(v); setPage(0); }}><SelectTrigger id="filter-upper"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{t("全部", "All")}</SelectItem>{Object.keys(TRIGRAM_INFO).map(n => <SelectItem value={n} key={n}>{trigramLabel(n, lang)}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="filter-lower">{t("下卦", "Lower")}</Label><Select value={lower} onValueChange={v => { setLower(v); setPage(0); }}><SelectTrigger id="filter-lower"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">{t("全部", "All")}</SelectItem>{Object.keys(TRIGRAM_INFO).map(n => <SelectItem value={n} key={n}>{trigramLabel(n, lang)}</SelectItem>)}</SelectContent></Select></div><Button variant="ghost" onClick={() => { setQuery(""); setUpper("all"); setLower("all"); setPage(0); }}>{t("重置", "Reset")}</Button></div>
      <p className="book-results-count" role="status">{t(`找到 ${filtered.length} 卦 · 按传统卦序排列`, `${filtered.length} patterns · Traditional sequence`)}</p>
      {filtered.length ? <><div className="hexagram-catalog">{filtered.slice(page * 16, page * 16 + 16).map(h => <button className="hexagram-card" key={h.number} onClick={() => open("hexagram", h.number)} aria-label={t(`第 ${h.number} 卦 ${h.name}，上${h.upper}下${h.lower}`, `Pattern ${h.number}, ${h.name}, upper ${h.upper}, lower ${h.lower}`)}><div className="hex-card-top"><span>{String(h.number).padStart(2, "0")}</span><MiniHexagram lines={h.lines} /></div><h3>{h.name}<span>{HEXAGRAM_NOTES[h.number - 1].title}</span></h3><p>{t(`上${h.upper} · 下${h.lower}`, `${TRIGRAM_INFO[h.upper].image[1]} / ${TRIGRAM_INFO[h.lower].image[1]}`)}</p><span className="hex-card-note">{HEXAGRAM_NOTES[h.number - 1].summary[li]}</span></button>)}</div><div className="book-pagination"><Button variant="outline" disabled={page === 0} onClick={() => { setPage(p => p - 1); document.querySelector(".hexagram-filters")?.scrollIntoView({ block: "start" }); }}>{t("上一页", "Previous")}</Button><span>{page + 1} / {Math.ceil(filtered.length / 16)}</span><Button variant="outline" disabled={(page + 1) * 16 >= filtered.length} onClick={() => { setPage(p => p + 1); document.querySelector(".hexagram-filters")?.scrollIntoView({ block: "start" }); }}>{t("下一页", "Next")}</Button></div></> : <div className="book-empty"><Search /><h3>{t("没有找到对应的卦", "No matching patterns")}</h3><p>{t("试试卦名、数字，或放宽上下卦筛选。", "Try a name or number, or relax the trigram filters.")}</p></div>}
    </>}

    {route.tab === "hexagrams" && base && current && note && <>
      <div className="book-breadcrumb"><Button variant="ghost" onClick={() => open("hexagrams")}>{t("返回六十四卦", "Back to all patterns")}</Button><span>{t(`从第 ${base.number} 卦 ${base.name} 开始`, `Starting from ${base.name} · ${base.number}`)}</span></div>
      <div className="hex-detail-layout"><aside className="hex-detail-diagram"><p className="eyebrow">{moving.length ? t("当前变卦", "CHANGED PATTERN") : t("当前卦象", "CURRENT PATTERN")}</p><div className="hex-detail-identity"><span aria-hidden="true">{hexagramSymbol(current.number)}</span><h2>{current.name}</h2></div><p>{current.number} · {note.title}</p><div className="hex-trigram-caption">{t("上卦", "Upper")} {trigramLabel(current.upper, lang)}</div><div className="six-line-workbench" role="group" aria-label={t("六爻结构练习", "Six-line structural exercise")}>
        {[...current.lines].reverse().map((line, i) => { const n = 6 - i; return <button key={n} disabled={building} className={`workbench-line ${moving.includes(n) ? "is-moving" : ""} ${n > revealed ? "not-revealed" : ""}`} onClick={() => setMoving(ms => ms.includes(n) ? ms.filter(m => m !== n) : [...ms, n].sort((a, b) => a - b))} aria-pressed={moving.includes(n)} aria-label={t(`第 ${n} 爻，${line ? "阳" : "阴"}，点击切换`, `Line ${n}, ${line ? "solid" : "broken"}, toggle`)}><span className={`line-stroke ${line ? "yang" : "yin"}`}><i />{!line && <i />}</span><span>{n}</span></button>; })}
      </div><div className="hex-trigram-caption">{t("下卦", "Lower")} {trigramLabel(current.lower, lang)}</div><p className="workbench-hint">{t("点任一爻切换阴阳，高亮标出改动的位置。", "Toggle any line. Highlights mark your changes.")}</p><div className="workbench-actions"><Button variant="outline" onClick={animate} disabled={building}><Play size={16} />{t("演示生成", "Build the pattern")}</Button><Button variant="ghost" onClick={() => { setMoving([]); setRevealed(6); setBuilding(false); }}><RotateCcw size={16} />{t("还原", "Restore")}</Button></div><div className="pattern-transition"><strong>{base.name}</strong><span>{t("结构变化", "changes to")}</span><strong>{current.name}</strong></div><p className="fine-print">{t(`变化位置：${moving.join("、") || "无"}。手动结构练习，不根据问题生成预测。`, `Changed positions: ${moving.join(", ") || "none"}. Manual structural study, independent of a question.`)}</p><Button onClick={() => onKeep(patternSnapshot(current.number, base.number, moving))}><Bookmark size={17} />{t("留进手记", "Keep in journal")}</Button></aside>
      <article className="hex-detail-text"><section className="book-reading-section"><span className="content-label">{t("古籍原文 · 卦辞", "CLASSICAL TEXT · JUDGMENT")}</span><p className="classical-judgment" lang="zh-Hant">{current.judgment}</p><a className="source-link" href={current.source} target="_blank" rel="noreferrer"><ExternalLink size={15} />{t("核对原文与版本", "Inspect the original and revision")}</a><p className="fine-print">{t("保留所见繁体原文及标点；不同版本可能有异文。", "Traditional characters and punctuation are preserved; editions may differ.")}</p></section><section className="book-reading-section"><span className="content-label">{t("白话导读 · 观象原创", "EDITORIAL NOTE · GUANXIANG")}</span><h3>{note.title}</h3><p>{note.summary[li]}</p><div className="book-exercise"><span>{t("留一个问题", "A QUESTION TO KEEP")}</span><p>{note.prompt[li]}</p></div><p className="fine-print">{t("导读概述传统主题，思考问题为编辑文字，均非逐字译文。", "The note summarizes a traditional theme; the prompt is editorial text. Neither is a literal translation.")}</p></section><section className="book-reading-section"><span className="content-label">{t("古籍原文 · 六爻", "CLASSICAL TEXT · SIX LINES")}</span><h3>{t("从下往上，逐爻读。", "Read upward, one position at a time.")}</h3><ol className="classical-lines">{current.lineTexts.map((text, i) => <li key={i} className={moving.includes(i + 1) ? "selected-line-text" : ""}><span>{i + 1}</span><p lang="zh-Hant">{text}</p></li>)}</ol>{current.extra.map(text => <p className="extra-line-text" key={text} lang="zh-Hant">{text}</p>)}<p className="fine-print">{t("此处为当前卦的爻辞。高亮仅标出结构改动，不自动选择断卦规则。", "These are the current pattern's line texts. Highlights show your structural edits, not an automatic interpretation rule.")}</p></section><div className="book-detail-navigation"><Button variant="outline" disabled={base.number === 1} onClick={() => open("hexagram", base.number - 1)}>{t("前一卦", "Previous pattern")}</Button><Button variant="ghost" onClick={() => open("learn", "iching-text")}><BookOpen size={17} />{t("怎样读卦辞与爻辞", "How to read these texts")}</Button><Button variant="outline" disabled={base.number === 64} onClick={() => open("hexagram", base.number + 1)}>{t("后一卦", "Next pattern")}</Button></div></article></div>
    </>}

    {route.tab === "learn" && !lesson && <><div className="book-intro-row"><div><h2>{t("每条路径，四个小步骤。", "Four small steps in each path.")}</h2><p>{t("从认识名词到亲手练习，再留下自己的记录。", "Move from terms to practice, then leave your own record.")}</p></div>{topicPicker}</div><div className="learning-paths">{TOPICS.filter(p => inTopic(p.id)).map(topic => <section className={`learning-path path-${topic.id}`} key={topic.id}><header><span>{topic.id === "iching" ? "䷰" : topic.id === "zodiac" ? "♎︎" : "E / I"}</span><div><h3>{topic.label[li]}</h3><p>{topic.description[li]}</p></div></header><ol>{LESSONS.filter(l => l.topic === topic.id).map((l, i) => <li key={l.id}><button onClick={() => open("learn", l.id)}><span>{String(i + 1).padStart(2, "0")}</span><div><strong>{l.title[li]}</strong><p>{l.summary[li]}</p></div><BookOpen size={17} aria-hidden="true" /></button></li>)}</ol></section>)}</div></>}
    {route.tab === "learn" && lesson && (() => { const path = LESSONS.filter(l => l.topic === lesson.topic); const index = path.findIndex(l => l.id === lesson.id); return <>
      <div className="book-breadcrumb"><Button variant="ghost" onClick={() => open("learn", lesson.topic)}>{t("返回学习路径", "Back to the path")}</Button><span>{topicLabel(lesson.topic)} · {index + 1} / 4</span></div><article className="lesson-paper"><header><span className="content-label">{t("观象原创入门", "ORIGINAL INTRODUCTION")}</span><h2>{lesson.title[li]}</h2><p>{lesson.summary[li]}</p></header>{lesson.sections.map((section, i) => <section className="lesson-section" key={i}><span>0{i + 1}</span><div><h3>{section.title[li]}</h3><p>{section.text[li]}</p></div></section>)}<div className="book-exercise"><span>{t("练一小步", "ONE SMALL EXERCISE")}</span><p>{lesson.exercise[li]}</p><Button variant="outline" onClick={() => lesson.topic === "iching" ? open("hexagram", 49) : onGo(lesson.topic)}>{t("去试一试", "Try it")}</Button></div>{lesson.sources.length > 0 && <div className="lesson-sources"><span>{t("继续核对与阅读", "REFERENCES & FURTHER READING")}</span>{lesson.sources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer"><ExternalLink size={15} />{source.title}</a>)}</div>}<div className="book-detail-navigation"><Button variant="outline" disabled={index === 0} onClick={() => open("learn", path[index - 1].id)}>{t("前一篇", "Previous lesson")}</Button><span>{index + 1} / 4</span>{index < 3 ? <Button onClick={() => open("learn", path[index + 1].id)}>{t("下一篇", "Next lesson")}</Button> : <Button onClick={() => onGo(lesson.topic)}>{t("开始实践", "Put it into practice")}</Button>}</div></article>
    </>; })()}

    {route.tab === "terms" && <><div className="book-intro-row"><div><h2>{t("遇见陌生词，停一下。", "Pause at an unfamiliar term.")}</h2><p>{t("短定义、一个例子，再连接到完整的入门内容。", "A short definition, an example, and a lesson to continue.")}</p></div>{topicPicker}</div><div className="book-filter-row">{search(t("搜索术语，例如动爻、太阳星座、E/I", "Search terms, such as moving line, Sun sign, or E/I"))}<span role="status">{terms.length} {t("条", "terms")}</span></div><div className="term-grid">{terms.map(term => <article className="term-card" key={term.id}><span className={`topic-chip chip-${term.topic}`}>{topicLabel(term.topic)}</span><h3>{term.term[li]}</h3><p>{term.meaning[li]}</p><div className="term-example">{term.example[li]}</div><button className="source-link" onClick={() => open("learn", term.lesson)}>{t("读完整解释", "Read the full explanation")}<BookOpen size={15} /></button></article>)}</div>{!terms.length && <div className="book-empty"><p>{t("没有匹配的术语，试试更短的关键词。", "No matching terms. Try a shorter keyword.")}</p></div>}<section className="book-faq"><h2>{t("常见问题", "Common questions")}</h2><div>{[
      [t("输入问题会改变卦象吗？", "Does a question change the pattern?"), t("不会。探索页是固定学习示例，卦典是手动结构练习。两处均会明确显示所用方式。", "No. The explorer uses fixed examples; the library offers manual structural study. The method is shown in each."), "iching-reading"],
      [t("这里使用实时天象吗？", "Are these live planetary readings?"), t("星座页使用原创娱乐文案，按星座和本地日期轮换，没有读取实时行星位置。", "The zodiac page rotates original entertainment copy by sign and local date. It does not use live planetary positions."), "zodiac-chart"],
      [t("这是官方 MBTI 测评吗？", "Is this the official MBTI assessment?"), t("这是二十四题原创情境练习。方法、计分和官方资料入口均在 MBTI 页面说明。", "This is an original 24-scenario exercise. Its method, scoring, and official references are explained on the MBTI page."), "mbti-score"],
      [t("为什么保存时保留日期与方法？", "Why keep the date and method?"), t("以后结果或理解可能变化。保留当时的文字、分数与方法，回看才有清楚的参照。手记仍存放在本设备的浏览器中。", "Readings and interpretations may change. Keeping the original wording, scores, and method gives later reviews a reference. Entries remain in this device's browser."), "mbti-review"],
    ].map(([question, answer, id]) => <article key={id}><h3>{question}</h3><p>{answer}</p><button className="source-link" onClick={() => open("learn", id)}>{t("了解更多", "Read more")}</button></article>)}</div></section></>}

    {route.tab === "resources" && <><div className="book-intro-row"><div><h2>{t("先知道它是什么，再开始读。", "Know the resource before you read.")}</h2><p>{t("原典、官方框架与原创入门，保留作者、版本和访问说明。", "Classics, official frameworks, and original lessons, with authors and access notes.")}</p></div>{topicPicker}</div><div className="book-filter-row">{search(t("搜索书名、作者或资料主题", "Search titles, authors, or topics"))}<span role="status">{resources.length} {t("份资料", "resources")}</span></div><div className="resource-grid">{resources.map(resource => <article className="resource-card" key={resource.id}><div><span className={`topic-chip chip-${resource.topic}`}>{topicLabel(resource.topic)}</span><span>{resource.level[li]}</span></div><BookOpen className="resource-icon" size={28} aria-hidden="true" /><h3>{resource.title[li]}</h3><p>{resource.description[li]}</p><dl><div><dt>{t("作者／整理者", "Author / editor")}</dt><dd>{resource.author[li]}</dd></div><div><dt>{t("版本／形式", "Edition / format")}</dt><dd>{resource.edition[li]} · {resource.format[li]}</dd></div><div><dt>{t("访问说明", "Access")}</dt><dd>{resource.access[li]}</dd></div></dl>{resource.href.startsWith("#") ? <Button variant="outline" onClick={() => open("learn", resource.topic)}>{t("站内阅读", "Read here")}</Button> : <a className="resource-read" href={resource.href} target="_blank" rel="noreferrer">{t("打开原站", "Open the source")}<ExternalLink size={16} /></a>}</article>)}</div>{!resources.length && <div className="book-empty"><p>{t("没有匹配的资料，换一个关键词或分类。", "No matching resources. Try another keyword or topic.")}</p></div>}<p className="book-editorial-note">{t("资料链接经本次核对；外部页面可能变动。这里提供阅读导航，不转载付费课程或现代解读。", "Links were checked for this edition; external pages may change. This is a reading guide rather than a copy of paid courses or modern commentaries.")}</p></>}

    {route.tab === "cases" && !caseStudy && <><div className="book-intro-row"><div><h2>{t("看一次，完整的记录。", "See a complete record.")}</h2><p>{t("三个原创虚构教学案例，练习区分事实、解释和实际反馈。", "Three original fictional teaching cases, separating facts, interpretation, and later feedback.")}</p></div>{topicPicker}</div><div className="case-grid">{CASES.filter(c => inTopic(c.topic)).map(c => <button className="case-card" key={c.id} onClick={() => open("cases", c.id)}><span className={`topic-chip chip-${c.topic}`}>{topicLabel(c.topic)}</span><h3>{c.title[li]}</h3><p>{c.question[li]}</p><span className="case-fiction-label">{t("原创虚构 · 教学示例", "Original fiction · Teaching example")}</span><span className="source-link">{t("查看记录过程", "Read the record")}<BookOpen size={16} /></span></button>)}</div></>}
    {route.tab === "cases" && caseStudy && <><div className="book-breadcrumb"><Button variant="ghost" onClick={() => open("cases")}>{t("返回案例", "Back to cases")}</Button><span>{topicLabel(caseStudy.topic)}</span></div><article className="lesson-paper case-paper"><header><span className="content-label">{t("原创虚构教学案例 · 不是真实用户反馈", "ORIGINAL FICTION · NOT A USER TESTIMONIAL")}</span><h2>{caseStudy.title[li]}</h2><p>{caseStudy.question[li]}</p></header>{[
      [t("已知事实", "Known facts"), caseStudy.facts[li]], [t("所用方式", "Method"), caseStudy.method[li]], [t("个人理解", "Interpretation"), caseStudy.interpretation[li]], [t("另一种可能", "Another possibility"), caseStudy.alternative[li]], [t("下一小步", "One small action"), caseStudy.action[li]], [t("后续回看", "Later review"), caseStudy.review[li]],
    ].map(([title, text], i) => <section className="lesson-section" key={title}><span>0{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></section>)}<div className="book-exercise"><span>{t("换成自己的处境，再记录一次。", "TRY YOUR OWN CONTEXT")}</span><p>{t("保留结构，重新填写自己的事实、理解与动作。", "Keep the structure and use your own facts, interpretation, and action.")}</p><Button onClick={() => onKeep({ kind: "reflection", title: ["案例练习：" + caseStudy.title[0], "Case exercise: " + caseStudy.title[1]], summary: ["参考虚构案例问题：" + caseStudy.question[0], "Fictional example question: " + caseStudy.question[1]], method: ["原创虚构案例练习；示例反馈不是本人经历。", "Original fictional case exercise; sample feedback is not your experience."], capturedAt: new Date().toISOString() })}><Bookmark size={17} />{t("建立自己的手记", "Start your own record")}</Button><Button variant="outline" onClick={() => open("learn", caseStudy.lesson)}>{t("阅读相关入门", "Read the related lesson")}</Button></div></article></>}
    </TabsContent></Tabs>
  </section>;
}
