export type Copy = [string, string];
export type Topic = "iching" | "zodiac" | "mbti";
export const TOPICS: { id: Topic; label: Copy; description: Copy }[] = [
  { id: "iching", label: ["卦象", "I Ching"], description: ["读结构、原文与变化", "Structure, text, and change"] },
  { id: "zodiac", label: ["星座", "Zodiac"], description: ["了解星座，使用每日灵感", "Context for signs and daily inspiration"] },
  { id: "mbti", label: ["人格探索", "Personality"], description: ["从四组偏好回到日常情境", "Four pairs in everyday situations"] },
];
const CLASSIC = { title: "《周易》· 维基文库", url: "https://zh.wikisource.org/wiki/周易" };
const FOUNDATION = { title: "Myers & Briggs Foundation", url: "https://www.myersbriggs.org/my-mbti-personality-type/myers-briggs-overview/" };
const OFFICIAL = { title: "The Myers-Briggs Company", url: "https://www.themyersbriggs.com/en-US/Access-Resources/All-About-the-MBTI-Assessment" };
const NASA = { title: "NASA Space Place · Constellations", url: "https://spaceplace.nasa.gov/constellations/en/" };
const DATES = { title: "Horoscope.com · Zodiac dates", url: "https://www.horoscope.com/horoscope-dates/" };
export type Lesson = { id: string; topic: Topic; title: Copy; summary: Copy; sections: { title: Copy; text: Copy }[]; exercise: Copy; sources: { title: string; url: string }[] };
export const LESSONS: Lesson[] = [
  { id: "iching-lines", topic: "iching", title: ["先读懂六条线", "Read the six lines"], summary: ["阴阳、爻位与上下卦，从结构开始。", "Begin with lines, positions, and trigrams."], sections: [
    { title: ["两种线，六个位置", "Two lines, six positions"], text: ["完整的一条线称阳爻，断开的两段称阴爻。一个卦由六爻构成，从最下方开始数：初、二、三、四、五、上。屏幕上的顺序虽然从上往下排列，阅读和生成的次序仍从下往上。", "A solid line is yang; a broken line is yin. Count six positions from the bottom: first, second, third, fourth, fifth, and top. A displayed pattern is read and built upward from its lowest line."] },
    { title: ["三爻组成一个经卦", "Three lines form a trigram"], text: ["下方三爻构成下卦，上方三爻构成上卦。乾、坤、震、巽、坎、离、艮、兑共八种经卦，各有天、地、雷、风、水、火、山、泽的传统意象。八种下卦与八种上卦组合，形成六十四卦。", "The lower three lines form the lower trigram and the upper three the upper trigram. The eight trigrams combine in 64 ways. Their traditional images are Heaven, Earth, Thunder, Wind, Water, Fire, Mountain, and Lake."] },
    { title: ["在图上亲手试一次", "Try it in the diagram"], text: ["打开六十四卦中的任意条目，点一条线切换阴阳。每次改变后，上下卦与卦名会一起更新。这里演示的是结构变化；问题文字不会决定线条。", "Open any entry in the hexagram library and toggle a line. The name and trigrams update with the structure. This is a structural demonstration; question text does not determine the lines."] },
  ], exercise: ["先找最下方的初爻，再说出当前的上卦与下卦。", "Locate the bottom line, then identify the upper and lower trigrams."], sources: [CLASSIC] },
  { id: "iching-change", topic: "iching", title: ["本卦、变卦与动爻", "Original, changed, and moving lines"], summary: ["一条线改变之后，发生了什么？", "What changes when a line changes?"], sections: [
    { title: ["先保存原来的结构", "Keep the original structure"], text: ["变化前的结构叫本卦。指定需要变化的爻后，把阳爻换为阴爻、阴爻换为阳爻，得到变卦，也称之卦。图中高亮的位置就是本次选择的动爻。", "The starting pattern is the original hexagram. Toggle selected moving lines between solid and broken to produce the changed hexagram. Highlighted positions mark the changes you selected."] },
    { title: ["动爻可以不止一条", "More than one line can move"], text: ["六个位置可以分别改变。不同的传统方法对如何得到动爻、如何选读爻辞有不同规则，不能把某一种规则自动当作所有方法的共同规则。书阁只让你观察结构，并明确显示改变的位置。", "Each of the six positions can change. Traditional methods differ in how moving lines are obtained and interpreted. The library makes structural changes visible without claiming one interpretation rule applies to every method."] },
    { title: ["用革与咸练习", "Practice with Ge and Xian"], text: ["革卦上兑下离。只把最下方的阳爻改成阴爻，下卦由离变为艮，上卦仍是兑，整体成为咸。另五爻保持原样。卦象探索中的观梅复算展示这一固定例子。", "Ge has Lake above Fire. Changing only its bottom line from solid to broken turns Fire into Mountain while Lake remains, producing Xian. The plum blossom replay demonstrates this fixed example."] },
  ], exercise: ["把革卦初爻改动一次，再恢复；比较变化前后的下卦。", "Change Ge's bottom line and restore it. Compare the lower trigram."], sources: [CLASSIC,{ title: "《梅花易数》· 观梅占", url: "https://www.eee-learning.com/book/4080" }] },
  { id: "iching-text", topic: "iching", title: ["卦辞、爻辞与导读", "Judgments, line texts, and notes"], summary: ["分清原文、解释与自己的理解。", "Separate the text, commentary, and your reading."], sections: [
    { title: ["读整卦，也读具体位置", "Read the whole and the position"], text: ["卦辞概述一卦的处境；爻辞按六个位置展开。初九、九二中的“九”对应阳爻，初六、六二中的“六”对应阴爻。乾的用九、坤的用六另列，它们不是第七个爻位。", "The judgment addresses the whole hexagram; line texts address its positions. Nine denotes a yang line and six a yin line. Qian's Use of Nine and Kun's Use of Six are additional texts, not seventh line positions."] },
    { title: ["版本与字词需要留意", "Pay attention to the version"], text: ["古籍在字形、异文与标点上可能不同。书阁保留所核对版本的繁体原文，并提供固定版本出处；卦名与检索另用常见简体写法。遇到不熟悉的字词，先对照上下文，再查原页。", "Ancient editions differ in characters, variants, and punctuation. The library preserves the checked traditional-character text and links to its revision. Common simplified names are also searchable."] },
    { title: ["白话导读不是逐字译文", "Notes are not literal translations"], text: ["观象的导读概述传统主题，再提出当代思考问题。它与古籍原文分开显示，不把编辑文字伪装成原句。读完以后，仍要回到你自己能够确认的事实与条件。", "Guanxiang notes summarize traditional themes and offer contemporary reflection questions. They are displayed separately from the original text and are not literal translations. Return to facts and conditions you can check."] },
  ], exercise: ["任选一个条目，指出哪段是古籍原文、哪段是观象导读。", "Choose an entry and identify the original text and the Guanxiang note."], sources: [CLASSIC] },
  { id: "iching-reading", topic: "iching", title: ["完整阅读一个卦", "Read a hexagram from start to finish"], summary: ["结构、原文、背景与回看，走完一次。", "Connect structure, text, context, and review."], sections: [
    { title: ["先确认结构与方法", "Start with structure and method"], text: ["记下卦名、上下卦、是否有动爻，以及卦象从哪里来。固定示例、手动结构练习与传统起卦是不同的过程。方法明确，才能知道哪些文字与当前过程有关。", "Record the name, trigrams, moving lines, and where the pattern came from. A fixed example, manual structural exercise, and traditional casting are different processes. Naming the method keeps the reading clear."] },
    { title: ["给现实背景留位置", "Include the actual context"], text: ["阅读导读时，可以写下联想到的事情，再把事实和联想分别记录。例如“明天要讨论方案”是背景，“这个卦让我想重新听听意见”是个人理解。两者可以有关联，也需要各自清楚。", "Write down the situation a note brings to mind, separating facts from associations. 'We discuss the plan tomorrow' is context; 'this reading makes me want to listen again' is your interpretation."] },
    { title: ["留下一个可回看的动作", "Leave one reviewable action"], text: ["结果页的“留进手记”会保存当前结构和方法说明。补一个可执行的小动作，之后追加回看，记录实际发生的事。保留符合和不符合预期的部分，才能看到阅读对你有什么真实作用。", "Keep the result in your journal with its structure and method. Add a small action and later append what happened, including what differed from your expectations."] },
  ], exercise: ["读完一个卦后，写下一件事实、一个理解和一个小动作。", "After reading, write one fact, one interpretation, and one action."], sources: [CLASSIC] },
  { id: "zodiac-sign", topic: "zodiac", title: ["十二星座，从哪里开始", "Where to start with the twelve signs"], summary: ["选择、日期与边界，先了解页面的用法。", "Selection, dates, and boundaries."], sections: [
    { title: ["这里怎样选择", "Choosing on this site"], text: ["星座页面按十二个常见太阳星座提供浏览入口。你可以直接选择想读的星座，不需要填写生日。本页不会据此生成完整出生星盘。", "The zodiac page offers the twelve conventional sun signs. Choose the sign you want to read without entering a birthday. The page does not generate a birth chart."] },
    { title: ["日期是一份参考", "Dates are a reference"], text: ["卡片使用常见日期区间。若出生在区间边界，太阳进入星座的时刻会随年份与时区变化，仅凭日期标签不能精确确认边界。这里的区间用于选择阅读内容。", "Cards show conventional date ranges. Near a boundary, the Sun's entry time varies by year and time zone. These ranges are a reading selector, not a precise boundary calculation."] },
  ], exercise: ["选择一个星座，观察整体提示与今日小事怎样关联。", "Choose a sign and compare its theme with its suggested small action."], sources: [DATES] },
  { id: "zodiac-chart", topic: "zodiac", title: ["太阳星座与完整星盘", "A sun sign and a birth chart"], summary: ["一个星座标签，包含多少信息？", "How much information does one label contain?"], sections: [
    { title: ["单个标签与多个位置", "One label and multiple positions"], text: ["太阳星座是占星传统中的一个标签。传统出生星盘还会谈到月亮、其他行星、上升点和宫位等内容，并需要明确的出生时间与地点。它与只选一个星座的每日文案是不同的产品。", "A sun sign is one label in astrological tradition. A traditional birth chart also refers to the Moon, other planets, an ascendant, and houses, using birth time and location. It differs from selecting a daily sign reading."] },
    { title: ["观象现在提供什么", "What Guanxiang offers here"], text: ["当前星座内容是观象原创娱乐提示，按选择的星座与设备本地日期轮换；没有读取实时行星位置。页面保存的是这份提示的文字和日期，而不是天象计算结果。", "Current readings are original entertainment prompts rotated by your selected sign and device date. No live planetary positions are used. A saved result captures the prompt and date, not a planetary calculation."] },
  ], exercise: ["在保存前，用一句话说明这份阅读是怎样产生的。", "Before saving, explain in one sentence how this reading was produced."], sources: [DATES] },
  { id: "zodiac-sky", topic: "zodiac", title: ["星座故事与真实星空", "Sign stories and the actual night sky"], summary: ["把文化故事与天文观察分别看清。", "Give stories and astronomical observation their own space."], sections: [
    { title: ["图案是从地球看见的", "Patterns seen from Earth"], text: ["我们把天空中的星点连成图案，也用故事记住它们。看起来相邻的恒星，在空间中的距离可能相差很大。能够看见哪些星座，还取决于观察地点、季节和时刻。", "People connect visible stars into patterns and remember them through stories. Stars that appear near one another may be far apart in space. What you can see depends on your location, season, and time."] },
    { title: ["两种不同的阅读方式", "Two ways of reading"], text: ["天文学用观测与数据研究天体；占星故事以文化符号组织解释。星座运势适合作为娱乐或反思提示；想看真实星空，可以从 NASA 的星座与观星资料开始。", "Astronomy studies celestial objects through observations and data. Astrological stories organize interpretations through cultural symbols. For actual skywatching, begin with NASA's constellation resources."] },
  ], exercise: ["今晚若条件允许，辨认一个可见星群，并记录地点和时刻。", "If conditions allow, identify a visible star pattern and note your location and time."], sources: [NASA] },
  { id: "zodiac-journal", topic: "zodiac", title: ["把每日提示写成自己的记录", "Turn a daily prompt into your own record"], summary: ["从一句提示，回到真实的一天。", "Bring a prompt back to your actual day."], sections: [
    { title: ["先问是否贴合", "Check whether it fits"], text: ["读到一句提醒时，先问它是否适合今天的具体处境。觉得有帮助，可以改成一个小动作；不贴合也可以直接记下。你不需要为了符合阅读而改变对事实的描述。", "Ask whether a reminder fits today's situation. If useful, turn it into a small action. If not, record that too. Keep the facts as they happened."] },
    { title: ["保存日期与当时文字", "Keep the date and wording"], text: ["星座页的保存按钮会把星座、日期、主题和当时的提示带进手记。之后日期改变，旧手记仍保留那一天的内容。追加回看时，可以记录做了什么、感受怎样、哪些期待并未发生。", "Saving captures the sign, date, theme, and current wording. The entry keeps that day's reading when the date changes. A later review can record actions, feelings, and expectations that did not occur."] },
  ], exercise: ["把今天的一件小事改写成你自己愿意执行的动作。", "Rewrite today's suggested small action as something you choose to do."], sources: [] },
  { id: "mbti-pairs", topic: "mbti", title: ["四组偏好，四种观察角度", "Four preference pairs"], summary: ["E/I、S/N、T/F、J/P 分别在问什么？", "What do E/I, S/N, T/F, and J/P ask?"], sections: [
    { title: ["注意与信息", "Attention and information"], text: ["E/I 关注外部互动与内部思考的偏好；S/N 关注具体信息与整体联系。想一个近期情境，再观察自己通常从哪边开始，比只凭一个标签更具体。", "E/I concerns outward interaction and inward reflection; S/N concerns concrete information and broader connections. Consider where you tend to start in a recent situation."] },
    { title: ["判断与安排", "Decisions and arrangements"], text: ["T/F 关注作判断时先考虑的理由与价值；J/P 关注明确安排与保持开放的偏好。两边都可以被使用，字母也不表示聪明程度、善良程度或能力排名。", "T/F concerns reasons and values in making judgments; J/P concerns settled arrangements and openness. Both sides are available and do not rank intelligence, kindness, or ability."] },
  ], exercise: ["选择一组偏好，写下一个支持倾向、一个不支持倾向的日常例子。", "For one pair, note an example that fits and one that does not."], sources: [FOUNDATION] },
  { id: "mbti-score", topic: "mbti", title: ["接近中间的分数怎么读", "Reading close or tied scores"], summary: ["先理解本次答案，再理解字母。", "Understand the answers before the letters."], sections: [
    { title: ["观象怎样计分", "How this exercise scores"], text: ["每组偏好有六道原创情境题。很像一边计两分，偏向一边计一分，中间项计零分；反向题按对应方向累加。本次两边同分时记 X，保留两种可能。差距一至两分时标为差距较小。", "Each pair has six original scenarios. Strong choices score two points, leaning choices one, and middle choices zero, accounting for each question's direction. Ties remain X; gaps of one or two points are marked small."] },
    { title: ["分差不是概率", "A gap is not a probability"], text: ["分数描述这二十四次回答，不能直接变成类型准确率。接近中间时，可以回到题目想想：是不是两种做法都常用，或者情境本身让你难以选择？观象自测不是官方 MBTI 量表。", "Scores describe these 24 answers, not a probability of type accuracy. A close pair invites a return to the scenarios: do both approaches fit, or was a question difficult to interpret? This is not the official MBTI instrument."] },
  ], exercise: ["找一组差距较小的分数，补充当时的情境与选择理由。", "For a close pair, add the situation and the reason behind your choices."], sources: [OFFICIAL] },
  { id: "mbti-context", topic: "mbti", title: ["同一种偏好，也有不同表现", "One preference in different settings"], summary: ["类型卡需要与日常经验一起读。", "Read a type card alongside your experience."], sections: [
    { title: ["选择受到情境影响", "Choices have a context"], text: ["独处写方案和当场带领讨论，可能让同一个人表现出不同做法。角色要求、熟悉程度、疲劳与时间压力，都值得在记录时写清楚。一次回答无需代表所有场合。", "Writing alone and leading a live discussion can invite different approaches from the same person. Note role demands, familiarity, tiredness, and time pressure. One answer need not stand for every setting."] },
    { title: ["把卡片当成观察问题", "Use cards as observation prompts"], text: ["读十六型图鉴时，把符合的描述对应到具体例子，也记录不符合的部分。相处与成长建议是观象原创练习，你可以选择适用的动作，并观察它是否帮助实际沟通。", "Connect a fitting card description to an actual example and record what does not fit. Guanxiang's relationship and growth prompts are original exercises; choose a fitting action and observe its effect."] },
  ], exercise: ["用同一件事，分别描述你独自处理与合作处理时的做法。", "Describe your approach to one task alone and when working with others."], sources: [FOUNDATION] },
  { id: "mbti-review", topic: "mbti", title: ["保存结果，再比较变化", "Save a result and compare it later"], summary: ["保留当时的四组分数与生活背景。", "Keep the four pairs and their context."], sections: [
    { title: ["保存的是这一次回答", "Keep this set of answers"], text: ["完成自测后，保存结果会记录当时的模式、四组分数、日期与方法。之后修改答案或重新开始，不会改写已经保存的手记。类型卡的浏览选择也不会替代自测结果。", "Saving records the current pattern, four pair scores, date, and method. Later edits or a restart do not rewrite saved journal entries. Browsing a type card does not replace your exercise result."] },
    { title: ["比较数字，也比较背景", "Compare context as well as numbers"], text: ["复测后先看每组偏好的变化，再看生活背景是否改变。工作角色、作答时想到的情境、选择中间项的数量，都是可记录的信息。变化值得了解，不必立即给自己换一个固定标签。", "After a repeat exercise, compare pair scores and the life context. Role changes, situations you considered, and middle answers can all be recorded. Explore a difference before treating it as a new fixed label."] },
  ], exercise: ["为本次结果补一句背景：最近的我主要在什么情境中？", "Add one context note: what settings have shaped my recent life?"], sources: [OFFICIAL] },
];

export type GlossaryTerm = { id: string; topic: Topic; term: Copy; meaning: Copy; example: Copy; lesson: string };
export const GLOSSARY: GlossaryTerm[] = [
  { id: "yang", topic: "iching", term: ["阳爻", "Yang line"], meaning: ["一条完整的线；爻辞位置常用“九”表示。", "A solid line, denoted by nine in line labels."], example: ["初九是最下方的阳爻。", "Initial Nine is a solid bottom line."], lesson: "iching-lines" },
  { id: "yin", topic: "iching", term: ["阴爻", "Yin line"], meaning: ["中间断开的两段线；爻辞位置常用“六”表示。", "A broken line, denoted by six in line labels."], example: ["六二是自下而上的第二条阴爻。", "Six in the second place is a broken second line."], lesson: "iching-lines" },
  { id: "trigram", topic: "iching", term: ["经卦 · 八卦", "Trigram"], meaning: ["三爻组成的结构，共八种。", "A three-line pattern, with eight possible combinations."], example: ["离的三爻由下至上为阳、阴、阳。", "Fire is solid, broken, solid from bottom to top."], lesson: "iching-lines" },
  { id: "hexagram", topic: "iching", term: ["重卦 · 六十四卦", "Hexagram"], meaning: ["上下两个经卦组合的六爻结构，共六十四种。", "Two trigrams form a six-line pattern, with 64 combinations."], example: ["上兑下离组成革。", "Lake above Fire forms Ge."], lesson: "iching-lines" },
  { id: "position", topic: "iching", term: ["爻位", "Line position"], meaning: ["从下向上编号的六个位置。", "One of six positions counted from bottom to top."], example: ["最上方叫上爻，最下方叫初爻。", "The top line is the upper line; the bottom is the initial line."], lesson: "iching-lines" },
  { id: "base", topic: "iching", term: ["本卦", "Original hexagram"], meaning: ["动爻变化之前保留的结构。", "The pattern before moving lines are changed."], example: ["观梅例中的本卦是革。", "Ge is the original pattern in the plum example."], lesson: "iching-change" },
  { id: "moving", topic: "iching", term: ["动爻", "Moving line"], meaning: ["在当前方法或演示中被指定改变阴阳的位置。", "A position selected to change between yin and yang."], example: ["革卦初爻改变后成为咸。", "Changing Ge's bottom line gives Xian."], lesson: "iching-change" },
  { id: "changed", topic: "iching", term: ["变卦 · 之卦", "Changed hexagram"], meaning: ["将指定动爻切换阴阳后得到的结构。", "The pattern produced after selected moving lines change."], example: ["乾的初爻由阳变阴，得到姤。", "Qian becomes Gou when its bottom line changes."], lesson: "iching-change" },
  { id: "judgment", topic: "iching", term: ["卦辞", "Judgment"], meaning: ["对应整卦的一段古籍文字。", "The classical text addressing the whole hexagram."], example: ["与分六个位置展开的爻辞区别阅读。", "Read it separately from the six position-specific line texts."], lesson: "iching-text" },
  { id: "line-text", topic: "iching", term: ["爻辞", "Line text"], meaning: ["对应某一爻位的古籍文字。", "The classical text associated with a line position."], example: ["潜龙勿用属于乾卦初九的爻辞。", "The hidden dragon text belongs to Qian's initial nine."], lesson: "iching-text" },
  { id: "sun-sign", topic: "zodiac", term: ["太阳星座", "Sun sign"], meaning: ["占星传统中按太阳所在黄道位置划分的标签。", "A traditional astrological label based on the Sun's zodiac position."], example: ["观象的十二星座入口采用常见太阳星座名称。", "The reading picker uses conventional sun-sign names."], lesson: "zodiac-sign" },
  { id: "cusp", topic: "zodiac", term: ["星座日期边界", "Date boundary"], meaning: ["两个日期区间交界附近；精确时刻会因年份和时区改变。", "The boundary between date ranges; exact entry times vary by year and time zone."], example: ["日期标签是浏览参考，不是精确星盘计算。", "Date labels are a browsing reference, not a precise chart calculation."], lesson: "zodiac-sign" },
  { id: "birth-chart", topic: "zodiac", term: ["出生星盘", "Birth chart"], meaning: ["占星传统中依据出生时间与地点组织的多个天体位置。", "An astrological arrangement of multiple positions based on birth time and location."], example: ["当前每日文案没有计算出生星盘。", "These daily readings do not calculate a birth chart."], lesson: "zodiac-chart" },
  { id: "constellation", topic: "zodiac", term: ["天文星座", "Astronomical constellation"], meaning: ["天文学中划分天空的区域，与日常星座运势的标签用途不同。", "A region of the sky used in astronomy, with a different purpose from a horoscope sign."], example: ["观看星空需要考虑地点、季节和时刻。", "Skywatching depends on location, season, and time."], lesson: "zodiac-sky" },
  { id: "daily", topic: "zodiac", term: ["每日原创提示", "Original daily prompt"], meaning: ["按星座与本地日期轮换的观象娱乐文案。", "Guanxiang entertainment copy rotated by sign and local date."], example: ["同一星座在同一天看到一致内容，主题会再次出现。", "A sign and date give a consistent reading; themes recur."], lesson: "zodiac-journal" },
  { id: "preference", topic: "mbti", term: ["偏好", "Preference"], meaning: ["这个框架里较自然的选择方向；不能当作能力排名。", "A more natural direction within the framework, not a ranking of ability."], example: ["同一个人也会使用一组偏好的两边。", "The same person can use both sides of a pair."], lesson: "mbti-pairs" },
  { id: "ei", topic: "mbti", term: ["E / I", "E / I"], meaning: ["外部互动与内部思考的偏好方向。", "A preference for outward interaction or inward reflection."], example: ["想一个需要理清想法的日常场景。", "Consider an everyday situation where you clarify your thoughts."], lesson: "mbti-pairs" },
  { id: "sn", topic: "mbti", term: ["S / N", "S / N"], meaning: ["具体信息与整体联系的偏好方向。", "A preference for concrete information or broader connections."], example: ["你较常先看细节，还是先看可能的联系？", "Do you often begin with details or possible connections?"], lesson: "mbti-pairs" },
  { id: "tf", topic: "mbti", term: ["T / F", "T / F"], meaning: ["判断时对逻辑理由与价值影响的偏好方向。", "A preference concerning reasoning and values in judgments."], example: ["它不是理性与情绪、聪明与不聪明的划分。", "It is not a split between intelligence and its absence."], lesson: "mbti-pairs" },
  { id: "jp", topic: "mbti", term: ["J / P", "J / P"], meaning: ["明确安排与保持开放的偏好方向。", "A preference for settled arrangements or keeping options open."], example: ["关注你如何处理计划与新信息。", "Observe how you handle plans and new information."], lesson: "mbti-pairs" },
  { id: "tie", topic: "mbti", term: ["X · 同分", "X · Tied pair"], meaning: ["观象自测两边分数一致，保留该维度的两种可能。", "The exercise's tied scores retain both possibilities for a pair."], example: ["XNTJ 表示 E/I 在本次作答中同分。", "XNTJ means E/I tied in this set of answers."], lesson: "mbti-score" },
  { id: "close", topic: "mbti", term: ["差距较小", "Small difference"], meaning: ["本次两边分差为一或两分，是观象的显示规则。", "A gap of one or two points, under this exercise's display rule."], example: ["分差不是类型的准确率。", "The gap is not a probability of a type being correct."], lesson: "mbti-score" },
];

export type Resource = { id: string; topic: Topic; title: Copy; author: Copy; edition: Copy; format: Copy; level: Copy; description: Copy; access: Copy; href: string };
export const RESOURCES: Resource[] = [
  { id: "zhouyi", topic: "iching", title: ["《周易》原典", "Zhou Yi · Classical text"], author: ["古籍佚名 · 维基文库整理", "Classical text · Wikisource"], edition: ["所见繁体文本；各卦链接固定版本", "Traditional text; entry links pin revisions"], format: ["在线原文", "Online text"], level: ["进阶", "Intermediate"], description: ["核对卦辞、爻辞与传统篇章。可先结合书阁导读阅读。", "Check judgments, line texts, and traditional chapters alongside the library notes."], access: ["原典公有领域；按原站说明使用编排内容", "Public-domain classical text; consult site terms for editorial material"], href: CLASSIC.url },
  { id: "plum", topic: "iching", title: ["《梅花易数》· 观梅占", "Mei Hua Yi Shu · Plum blossom example"], author: ["传统古籍 · 易学网整理", "Traditional text · EEE Learning"], edition: ["卷一 · 观梅示例", "Volume I · Fixed example"], format: ["在线古籍", "Online classic"], level: ["入门", "Beginner"], description: ["对照观象复算中的年、月、日、时数字与动爻。", "Compare the fixed inputs and moving line with the replay."], access: ["外部网页阅读；现代整理内容不转载", "Read externally; modern editorial material is not reproduced"], href: "https://www.eee-learning.com/book/4080" },
  { id: "nasa", topic: "zodiac", title: ["星座与真实星空", "What Are Constellations?"], author: ["NASA Space Place", "NASA Space Place"], edition: ["英文科普网页", "English educational page"], format: ["图文科普", "Illustrated article"], level: ["入门", "Beginner"], description: ["了解星群图案、观测地点与天文学的基本区别。", "Explore star patterns, observing locations, and astronomy."], access: ["免费外部阅读；内容与图片按原站条款使用", "Free external reading; consult original terms for reuse"], href: NASA.url },
  { id: "zodiac-dates", topic: "zodiac", title: ["太阳星座日期参考", "Sun-sign date reference"], author: ["Horoscope.com", "Horoscope.com"], edition: ["常见日期区间", "Conventional date ranges"], format: ["查询网页", "Reference page"], level: ["入门", "Beginner"], description: ["用于理解星座选择器的日期标签，不是完整星盘。", "Context for the picker date labels, rather than a complete chart."], access: ["外部浏览；未转载其运势文案", "External reading; its horoscope copy is not reproduced"], href: DATES.url },
  { id: "foundation", topic: "mbti", title: ["四组偏好框架介绍", "The four-pair framework"], author: ["Myers & Briggs Foundation", "Myers & Briggs Foundation"], edition: ["官方英文概览", "Official English overview"], format: ["框架说明", "Framework overview"], level: ["入门", "Beginner"], description: ["了解四组偏好与十六种组合；再回到自己的日常例子。", "Read about the four preference pairs and return to everyday examples."], access: ["免费外部阅读；不是本站自测的认证", "Free external reading; not a certification of this exercise"], href: FOUNDATION.url },
  { id: "official-mbti", topic: "mbti", title: ["官方 MBTI 量表说明", "The official MBTI assessment"], author: ["The Myers-Briggs Company", "The Myers-Briggs Company"], edition: ["官方英文资源页", "Official English resource"], format: ["方法说明", "Method overview"], level: ["入门", "Beginner"], description: ["认识官方工具与观象原创情境练习的区别。", "Understand the distinction between the official instrument and this original exercise."], access: ["说明页可阅读；官方测评服务另计", "Information page available; official assessment services are separate"], href: OFFICIAL.url },
  ...TOPICS.map(topic => ({ id: `original-${topic.id}`, topic: topic.id, title: [topic.label[0] + " · 原创入门四步", topic.label[1] + " · Four original lessons"] as Copy, author: ["观象", "Guanxiang"] as Copy, edition: ["2026-10-01 · 入门版", "2026-10-01 · Introductory edition"] as Copy, format: ["站内短读与练习", "On-site reading and exercises"] as Copy, level: ["入门", "Beginner"] as Copy, description: ["四篇有次序的短读，每篇都带一个可以实际完成的小练习。", "Four ordered lessons, each with a small exercise to try."] as Copy, access: ["站内完整阅读", "Available in full on this site"] as Copy, href: `#library/learn/${topic.id}` })),
];

export type CaseStudy = { id: string; topic: Topic; title: Copy; question: Copy; facts: Copy; method: Copy; interpretation: Copy; alternative: Copy; action: Copy; review: Copy; lesson: string };
export const CASES: CaseStudy[] = [
  { id: "change-a-plan", topic: "iching", title: ["方案要改，先听见不同意见", "Changing a plan and hearing other views"], question: ["团队方案遇到变化，我应该先理清什么？", "What should I clarify first when a team plan changes?"], facts: ["原计划由两人制定，新加入的同事指出一项遗漏。讨论将在明天进行。", "Two people made the original plan. A new colleague points out an omission. A discussion is scheduled for tomorrow."], method: ["固定观梅学习示例：革初爻变化为咸。问题没有参与起卦。", "Fixed plum blossom example: Ge changes to Xian at the bottom line. The question does not generate the pattern."], interpretation: ["革的更新主题让我先写清要改的部分；咸的相互影响主题让我想到先听遗漏是怎样被发现的。", "Ge's change theme suggests clarifying the revision; Xian's mutual response theme suggests listening to how the omission was found."], alternative: ["这也可能只是普通的方案信息补全，未必需要大幅改变。先核实遗漏，比急着给变化定性更有用。", "This may be an ordinary information gap rather than a major change. Verify the omission before deciding its scale."], action: ["会前列出已确认条件，邀请同事说明那项遗漏。", "List confirmed conditions and invite the colleague to explain the omission."], review: ["示范回看：遗漏确实存在，只修改了一个环节。原来担心的全面返工没有发生。", "Illustrative review: the omission was real, but only one step needed changing. The feared complete rework did not happen."], lesson: "iching-reading" },
  { id: "a-daily-reminder", topic: "zodiac", title: ["一条每日提示，变成一次明确沟通", "A daily reminder becomes a clear conversation"], question: ["最近一直忙，我可以怎样照顾一段关系？", "How can I attend to a relationship during a busy period?"], facts: ["两人最近错过了几次聊天，尚未约定下一次可以说话的时间。", "Two people have missed several conversations and have not agreed on the next time to talk."], method: ["阅读按星座与本地日期轮换的原创娱乐提示，主题是把约定说具体。", "An original entertainment prompt rotated by sign and date, about making an agreement concrete."], interpretation: ["提醒让我把“有空再聊”改为给出一个实际可用的时间。", "The reminder suggests replacing 'sometime' with an actual available time."], alternative: ["忙碌可能来自时间安排，也可能涉及不同的沟通需要。不能只凭一条提示判断对方的心意。", "Busy schedules or different communication needs may be involved. One prompt cannot establish the other person's intentions."], action: ["发出两个可选时间，问对方哪个更合适。", "Offer two available times and ask which works better."], review: ["示范回看：约定了时间，但聊天仍然较短。记录这个结果，下一次再确认彼此需要的交流方式。", "Illustrative review: a time was agreed, but the conversation was still brief. Keep that result and ask about preferred ways to connect."], lesson: "zodiac-journal" },
  { id: "different-settings", topic: "mbti", title: ["同一组偏好，两种工作情境", "One preference pair in two work settings"], question: ["为什么我有时想先独自思考，有时又想找人讨论？", "Why do I sometimes think alone and sometimes seek discussion?"], facts: ["写方案时先整理笔记；遇到不熟悉的操作时，通常直接找同事一起试。", "For a written plan, notes come first. For an unfamiliar operation, a colleague is usually invited to try it together."], method: ["原创偏好练习的 E/I 分差较小；结果不是官方 MBTI 量表。", "A small E/I gap in the original exercise; this is not the official MBTI instrument."], interpretation: ["本次分数提示我两种做法都在使用，不能只用一个字母描述所有情境。", "The scores suggest both approaches are in use; one letter does not describe every setting."], alternative: ["区别也可能来自任务熟悉程度和效率需要，不一定代表偏好本身发生了变化。", "Task familiarity or practical efficiency may explain the difference without implying a changed preference."], action: ["下次两类任务分别记录：我从哪种做法开始，为什么。", "For each kind of task, record the approach used first and why."], review: ["示范回看：熟悉任务独自处理更顺，不熟悉任务合作更快。保留具体例子，暂不急着换标签。", "Illustrative review: familiar tasks went smoothly alone; unfamiliar tasks were faster together. Keep the examples before changing labels."], lesson: "mbti-context" },
];
